local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("WaW Hub", "DarkTheme")
local Tab = Window:NewTab("Scripts")
local Section = Tab:NewSection("Update: 13 More Games To The List, Some Dont work!")
Section:NewButton("MSPAINT V2 Doors", "best doors script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/notpoiu/mspaint/main/main.lua"))()
end)
Section:NewButton("BLACKKING Doors", "2nd best doors script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/KINGHUB01/BlackKing-obf/main/Doors%20Blackking%20And%20BobHub"))()
end)
Section:NewButton("Omega's Doors Hub", "Credits to Omega0megaq", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/wAwStorage/Stuffeeezz/refs/heads/main/Omega0megaq%20Doors%20gui.lua"))()
end)
Section:NewButton("HARDCORE MODE DOORS", "I dont know if it supports pc but it supports mobile", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Kotyara19k-Doorsspawner/Hardcore/refs/heads/main/loaderNew.lua"))()
end)
Section:NewButton("FFJ1 Doors", "ffj1 i guess", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/FFJ1/Roblox-Exploits/main/scripts/Loader.lua"))()
end)
Section:NewButton("Yumiara's Doors Gui", "credits to yumiara?", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Yumiara/Python/main/Main.lua"))();
end)
Section:NewButton("Entity Spawner Doors", "maybe doeesnt wooork", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/wAwStorage/Stuffeeezz/refs/heads/main/entityspawner.lua"))()
end)
Section:NewButton("Giggle Spawner Doors", "maybe doeesnt wooork 2", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/wAwStorage/Stuffeeezz/refs/heads/main/giggle.lua"))()
end)
Section:NewButton("Doors Kardin Hong GUI", "includes spawn grumble and etc.", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/wAwStorage/Stuffeeezz/refs/heads/main/kardin.lua"))()
end)
Section:NewButton("Tsb Saitama To Gojo", "C-S: Effects, S-S: Animations, OP ULT", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/skibiditoiletfan2007/BaldyToSorcerer/main/Latest.lua"))()
end)
Section:NewButton("The Strongest Battlegrounds", "Op Tsb Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/DiosDi/VexonHub/main/TSB-VexonHub"))()
end)

Section:NewButton("Fling Things And People", "Op Ftap Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/VerbalHubz/Verbal-Hub/main/MoonyGui.lua",true))()
end)

Section:NewButton("Funky Friday", "its good but dont lag too much", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/wAwStorage/Stuffeeezz/refs/heads/main/funkyfriday.lua"))()
end)
Section:NewButton("(NEW) Arsenal", "shoot this fooleh", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Infinity2346/Tect-Menu/main/Arsenalscript.txt"))()
end)
Section:NewButton("(NEW) K.A.T", "cut this guys head off fucking nigger", function()
    loadstring(game:HttpGet("http://darkhub.xyz/remote-script.lua", true))()
end)
Section:NewButton("(NEW) MM2", "shit urself", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/tbao143/thaibao/main/TbaoHubMurderMystery2") )( )
end)
Section:NewButton("(NEW) Build A Boat For Treasure", "yes", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/WinterDinder/silver-couscous/main/masage.lua"))()
end)
Section:NewButton("(NEW) Brookhaven", "yessir", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/IceMael7/NewIceHub/main/Brookhaven"))()
end)
Section:NewButton("(NEW) Slap Battles", "yessirer", function()
    loadstring(game:HttpGet("https://scriptblox.com/raw/Slap-Battles-Open-source-for-9484"))()
end)
Section:NewButton("(NEW) Da hood", "fuck lil femboys up", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/lerkermer/lua-projects/master/SwagModeV002"))()
end)
Section:NewButton("(NEW) Item Asylum", "item asylumez", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/TwXsMX4S"))()
end)
Section:NewButton("(NEW) Jailbreak", "the fuck is a kilometer niggeeer", function()
    loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/730854e5b6499ee91deb1080e8e12ae3.lua"))()
end)
Section:NewButton("(NEW) 3008", "slavery", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt"))()
end)
Section:NewButton("Meme Sea", "auto farm good and stuff but has key", function()
    loadstring(game:HttpGet("https://discord0000.xyz/scripts/meme_sea"))()
end)
Section:NewButton("(NEW) Pet Simulator X", "skibidi", function()
    loadstring(game:HttpGetAsync("https://blacktrap.org/blacktrap/users/checkpoint/Auth.txt"))()
end)
Section:NewButton("(NEW) Pet Sim 99", "skibidi toyletyyy", function()
    loadstring(game:HttpGet('https://zaphub.xyz/Exec'))()
end)
Section:NewButton("(NEW) Murderers VS Sherrifs Duels", "skibidi toyletyyy destroyer", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/tbao143/thaibao/main/TbaoHubMurdervssheriff"))()
end)
Section:NewButton("UNC Test", "test ur executor", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/wAwStorage/Stuffeeezz/refs/heads/main/UNC%20test.lua"))()
end)
Section:NewButton("FE Chat Bypass", "say bad words", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/wAwStorage/Stuffeeezz/refs/heads/main/chat%20bypass.lua"))()
end)
Section:NewButton("Nameless Admin", "admin commands", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/FD2Team/Nameless-Admin-No-Byfron-Kick/main/Source",true))()
end)
Section:NewButton("Infinite Yield", "admin commands 2", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()
end)
Section:NewButton("(NEW) Aimbot", "right click to auto aim", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/wAwStorage/Stuffeeezz/refs/heads/main/aimbot.lua'))()
end)
local Section1 = Tab:NewSection("UI Settings")

Section1:NewKeybind("Toggle UI ", "what lol?", Enum.KeyCode.RightControl, function()
	Library:ToggleUI()
end)
