local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("WaW Hub", "DarkTheme")
local Tab69 = Window:NewTab("Info")
local Section69 = Tab69:NewSection("More Scripts Are Going To Be Added Soon...")
local Tab = Window:NewTab("Doors")
local Section = Tab:NewSection("Scripts")
Section:NewButton("MSPAINT V2", "best doors script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/notpoiu/mspaint/main/main.lua"))()
end)
Section:NewButton("BLACKKING", "2nd best doors script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/KINGHUB01/BlackKing-obf/main/Doors%20Blackking%20And%20BobHub"))()
end)
Section:NewButton("Omega's Doors Hub", "Credits to Omega0megaq", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/wAwStorage/Stuffeeezz/refs/heads/main/Omega0megaq%20Doors%20gui.lua"))()
end)
Section:NewButton("HARDCORE MODE", "I dont know if it supports pc but it supports mobile", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Kotyara19k-Doorsspawner/Hardcore/refs/heads/main/loaderNew.lua"))()
end)
Section:NewButton("FFJ1", "ffj1 i guess", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/FFJ1/Roblox-Exploits/main/scripts/Loader.lua"))()
end)
Section:NewButton("Yumiara's Doors Gui", "credits to yumiara?", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Yumiara/Python/main/Main.lua"))();
end)
Section:NewButton("Entity Spawner", "maybe doeesnt wooork", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/wAwStorage/Stuffeeezz/refs/heads/main/entityspawner.lua"))()
end)
Section:NewButton("Giggle Spawner", "maybe doeesnt wooork 2", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/wAwStorage/Stuffeeezz/refs/heads/main/giggle.lua"))()
end)
Section:NewButton("Kardin Hongs Scripts", "includes spawn grumble and etc.", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/wAwStorage/Stuffeeezz/refs/heads/main/kardin.lua"))()
end)
local Tab1 = Window:NewTab("Tsb")
local Section1 = Tab1:NewSection("Scripts")
Section1:NewButton("Saitama To Gojo", "C-S: Effects, S-S: Animations, OP ULT", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/skibiditoiletfan2007/BaldyToSorcerer/main/Latest.lua"))()
end)
Section1:NewButton("Vexon Hub", "Op Tsb Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/DiosDi/VexonHub/main/TSB-VexonHub"))()
end)
local Tab2 = Window:NewTab("Ftap")
local Section2 = Tab2:NewSection("Scripts")
Section2:NewButton("Verbal Hub", "Op Ftap Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/VerbalHubz/Verbal-Hub/main/MoonyGui.lua",true))()
end)
local Tab5 = Window:NewTab("Funky Friday")
local Section5 = Tab5:NewSection("Scripts")
Section5:NewButton("Auto Play", "its good but dont lag too much", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/wAwStorage/Stuffeeezz/refs/heads/main/funkyfriday.lua"))()
end)
local Tab6 = Window:NewTab("Meme Sea")
local Section6 = Tab6:NewSection("Scripts")
Section6:NewButton("OP Hub", "auto farm good and stuff but has key", function()
    loadstring(game:HttpGet("https://discord0000.xyz/scripts/meme_sea"))()
end)
local Tab3 = Window:NewTab("Misc")
local Section3 = Tab3:NewSection("Scripts")
Section3:NewButton("UNC Test", "test ur executor", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/wAwStorage/Stuffeeezz/refs/heads/main/UNC%20test.lua"))()
end)
Section3:NewButton("FE Chat Bypass", "say bad words", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/wAwStorage/Stuffeeezz/refs/heads/main/chat%20bypass.lua"))()
end)
Section3:NewButton("Nameless Admin", "admin commands", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/FD2Team/Nameless-Admin-No-Byfron-Kick/main/Source",true))()
end)
Section3:NewButton("Infinite Yield", "admin commands 2", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()
end)
local Section4 = Tab3:NewSection("UI Settings")

Section4:NewKeybind("Toggle UI ", "what lol?", Enum.KeyCode.RightControl, function()
	Library:ToggleUI()
end)
